---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: Infrastructure/AsCode
  children:
  - name: host-vm
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: ubuntu
    password: ubuntu
    children:
    - name: tomcat
      type: tomcat.Server
      home: /home/ubuntu/tomcat/tomcat-as-code
      startCommand: nohup /home/ubuntu/tomcat/tomcat-as-code/bin/startup.sh && sleep 5
      stopCommand: /home/ubuntu/tomcat/tomcat-as-code/bin/shutdown.sh
      children:
        - name: tomcat.vh
          type: tomcat.VirtualHost
    - name: sql-db
      type: sql.PostgreSqlClient
      username: scott
      password: tiger
      databaseName: petclinicDev
      postgreSqlHome: /usr
    - name: testRunner
      type: smoketest.Runner
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/Dev/AsCode
  children:
  - name: PetClinic Dictionary
    type: udm.Dictionary
    entries:
      TITLE: !value title
      logFilePath: /dev/null
      logRootLevel: DEBUG
      title: !value title
      logLevel: DEBUG
      timeout: 30
      smoke.test.url: http://deployit.vm:13080/petclinic/index.jsp
      tests2.ExecutedHttpRequestTest.url: '{{smoke.test.url}}'      
  - name: PetClinic DB Dictionary
    type: udm.Dictionary
    entries:
      tomcat.DataSource.driverClassName: com.mysql.jdbc.Driver
      tomcat.DataSource.url: jdbc:mysql://localhost/petclinic
      tomcat.DataSource.username: scott
      tomcat.DataSource.context: petclinic
    encryptedEntries:
      tomcat.DataSource.password: passwor
- name: Environments/Dev/Tomcat-Dev-AsCode
  type: udm.Environment
  members:
  - ~Infrastructure/AsCode/host-vm/tomcat/tomcat.vh
  - ~Infrastructure/AsCode/host-vm/sql-db
  - ~Infrastructure/AsCode/host-vm/tomcat
  - ~Infrastructure/AsCode/host-vm/testRunner
  - ~Infrastructure/AsCode/host-vm
  dictionaries:
  - ~Environments/Dev/AsCode/PetClinic Dictionary
  - ~Environments/Dev/AsCode/PetClinic DB Dictionary
