apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/Java/Services
  children:
  - name: cat-service
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      orchestrator:
        - sequential-by-dependency
      applicationDependencies:
          pet-service: '[1.0.0,2.0.0)'
      children:
      - name: cat-service-deployment
        type: k8s.DeploymentSpec
        containers:
        - name: cat-service
          type: k8s.ContainerSpec
          containerName: cat-service
          image: nginx
          ports:
          - name: web
            type: k8s.ContainerPortSpec
            containerPort: "80"
            exposeAsService: "false"
        podCreateDeleteRetryCount: "20"
        labels:
          app: cat-service
        restartPolicy: Always
        matchLabels:
          app: cat-service
      - name: cat-service-service
        type: k8s.ServiceSpec
        serviceName: cat-service
        selectors:
          app: cat-service
        ports:
        - name: http
          type: k8s.ServicePortSpec
          port: "80"
          targetPort: "8001"
      - name: cat-sql
        type: sql.SqlScripts
        file: !file "cat-sql"
